In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/stores-area-and-sales-data/Stores.csv
/kaggle/input/data-science-job-salaries/ds_salaries.csv


In [2]:
df = pd.read_csv("../input/stores-area-and-sales-data/Stores.csv")
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values
df.head()


Store ID   Store_Area  Items_Available  Daily_Customer_Count  Store_Sales
0          1        1659             1961                   530        66490
1          2        1461             1752                   210        39820
2          3        1340             1609                   720        54010
3          4        1451             1748                   620        53730
4          5        1770             2111                   450        46620

In [3]:
print(X)

[[   1 1659 1961  530]
 [   2 1461 1752  210]
 [   3 1340 1609  720]
 ...
 [ 894 1200 1436 1060]
 [ 895 1299 1560  770]
 [ 896 1174 1429 1110]]


In [4]:
print(y)

[ 66490  39820  54010  53730  46620  45260  72240  37720  46310  44150
  71280  57620  60470  59130  66360  78870  77250  38170  63540  40190
  43460  68890  52780  50680  41880  70050  25820  60530  78100  84860
  80140  14920  60460  74560  72430  45460  41570  62870  55170  45480
  49550  48140  67640  39730  35800  49270  66510  62530  59980  76350
  81820  57830  70450  67000  64090  48670  66210  83660  70770  53870
  71300  46100  49100  65920  58660  69130  49080  72710  33430  42430
  56650  33580  67370  71780  84840  82070  26770  65560  38660  65660
  40700  88910  57860  42670  90180  51280  97260  39650  45720  42060
  65350  67080  54030  56360  77120  50810  60960  61180  63660  41190
  78420  65580  89080  94170  50950  65180  69310  79210  23740  36330
  51700  62950  56010  45080  46830  64750  80780  31180  56710  49390
  66000  32770  46580  79780  35510  80970  61150  49210  79950  68740
  57480  72630  50070  40490  51850  42840  60940  62280  76530  85130
  4859

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [6]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [7]:
y_pred = regressor.predict(X_test)

In [8]:
print(y_pred)

[55677.3748764  58900.79495752 54950.05812072 58503.40230173
 56387.22289739 57305.29642639 63219.59327903 56814.31736888
 62173.0175871  60655.73858904 60017.34899553 58313.12307262
 61453.19026091 59436.77457492 62195.19236298 60124.04866905
 58011.86487515 57598.37142624 56042.80227906 60588.64485647
 61289.38188983 60155.60936422 60240.564149   55463.00944575
 57670.56052073 62522.30265006 60490.81618217 61904.7865028
 56059.59933994 61916.34176558 62014.16980879 55232.86327489
 56558.03709755 63729.17947994 57839.13658103 62004.63248265
 57827.52158061 61069.0346442  57909.87410158 61593.57838797
 57826.80002896 56421.43242122 61014.31179161 61630.06628616
 58194.13802115 58616.2086679  62590.78751303 59049.71960603
 57889.93251296 63378.79880341 56325.63149803 56612.18523909
 60800.50012305 58717.32111803 61562.48272369 58337.20515898
 58950.52360776 62097.41961362 53539.95110238 61310.38487964
 58886.60772017 56389.22053096 57959.10325364 56213.82368863
 59893.1082763  57761.713